name: Build and Public Docker Image

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        run: docker build -t sothearo/rest-servers .

      - name: Login to dockerHub
        run: docker login -u sothearo --password-stdin ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to dockerhub
        run: docker push sothearo/rest-servers
